import type { ThemeConfig } from 'antd';

export const designTokens = {
  colors: {
    primary: '#ae2f34',
    primaryContainer: '#ff6b6b',
    sunsetOrange: '#FF8A5B',
    onPrimary: '#ffffff',
    secondary: '#755a1d',
    secondaryContainer: '#fed88e',
    onSecondaryContainer: '#785d1f',
    tertiary: '#69519b',
    tertiaryContainer: '#a88ede',
    onTertiaryContainer: '#3d246c',
    emeraldGreen: '#4CAF8D',
    error: '#ba1a1a',
    errorContainer: '#ffdad6',
    onErrorContainer: '#93000a',
    background: '#f8f9ff',
    offWhite: '#FAFAFA',
    surface: '#ffffff',
    borderGray: '#E6EAF0',
    backgroundAlt: '#F5F7FA',
    onSurface: '#121c2a',
    onSurfaceVariant: '#584140',
    inverseSurface: '#27313f',
    inverseOnSurface: '#eaf1ff',
    surfaceContainerLow: '#eff4ff',
    surfaceContainer: '#e6eeff',
    surfaceContainerHigh: '#dee9fc',
    outline: '#8c706f',
    outlineVariant: '#e0bfbd',
  },
  typography: {
    headlineFont: "'Hanken Grotesk', sans-serif",
    bodyFont: "'Inter', sans-serif",
  },
  borderRadius: {
    sm: 4,
    default: 8,
    md: 12,
    lg: 16,
    xl: 24,
    full: 9999,
  },
  spacing: {
    base: 8,
    containerMargin: 32,
    gutter: 24,
    sectionGap: 64,
  },
  shadows: {
    level1: '0 4px 20px rgba(31, 41, 55, 0.08)',
    level2: '0 8px 32px rgba(31, 41, 55, 0.12)',
  },
} as const;

export const antTheme: ThemeConfig = {
  token: {
    colorPrimary: designTokens.colors.primary,
    colorSuccess: designTokens.colors.emeraldGreen,
    colorError: designTokens.colors.error,
    colorWarning: '#FF8A5B',
    colorInfo: designTokens.colors.tertiary,
    colorBgBase: designTokens.colors.background,
    colorBgContainer: designTokens.colors.surface,
    colorBgLayout: designTokens.colors.offWhite,
    colorBorder: designTokens.colors.borderGray,
    colorBorderSecondary: designTokens.colors.borderGray,
    colorText: designTokens.colors.onSurface,
    colorTextSecondary: designTokens.colors.onSurfaceVariant,
    fontFamily: designTokens.typography.bodyFont,
    fontSize: 14,
    fontSizeHeading1: 48,
    fontSizeHeading2: 32,
    fontSizeHeading3: 24,
    fontSizeHeading4: 18,
    fontSizeHeading5: 16,
    fontSizeLG: 16,
    fontSizeSM: 12,
    borderRadius: designTokens.borderRadius.default,
    borderRadiusLG: designTokens.borderRadius.lg,
    borderRadiusSM: designTokens.borderRadius.sm,
    controlHeight: 40,
    controlHeightLG: 48,
    controlHeightSM: 32,
    boxShadow: designTokens.shadows.level1,
    boxShadowSecondary: designTokens.shadows.level2,
    lineHeight: 1.5,
    padding: 16,
    paddingLG: 24,
    paddingSM: 12,
    paddingXS: 8,
    margin: 16,
    marginLG: 24,
    marginSM: 12,
    marginXS: 8,
  },
  components: {
    Layout: {
      siderBg: designTokens.colors.surface,
      headerBg: designTokens.colors.surface,
      bodyBg: designTokens.colors.offWhite,
      triggerBg: designTokens.colors.primary,
    },
    Menu: {
      itemBg: 'transparent',
      itemSelectedBg: 'rgba(174, 47, 52, 0.08)',
      itemSelectedColor: designTokens.colors.primary,
      itemHoverBg: 'rgba(174, 47, 52, 0.04)',
      itemHoverColor: designTokens.colors.primary,
      itemColor: designTokens.colors.onSurfaceVariant,
      iconSize: 18,
      itemHeight: 44,
      itemBorderRadius: designTokens.borderRadius.default,
    },
    Button: {
      borderRadius: designTokens.borderRadius.default,
      primaryShadow: '0 2px 8px rgba(174, 47, 52, 0.25)',
      defaultBorderColor: designTokens.colors.borderGray,
    },
    Card: {
      borderRadiusLG: designTokens.borderRadius.xl,
      boxShadowTertiary: designTokens.shadows.level1,
      paddingLG: 24,
    },
    Input: {
      activeBorderColor: designTokens.colors.primary,
      hoverBorderColor: designTokens.colors.primary,
      colorBgContainer: designTokens.colors.backgroundAlt,
      activeShadow: `0 0 0 2px rgba(174, 47, 52, 0.1)`,
      borderRadius: designTokens.borderRadius.default,
    },
    Select: {
      colorBgContainer: designTokens.colors.backgroundAlt,
      borderRadius: designTokens.borderRadius.default,
    },
    Table: {
      headerBg: designTokens.colors.offWhite,
      headerColor: designTokens.colors.onSurfaceVariant,
      borderColor: designTokens.colors.borderGray,
      rowHoverBg: 'rgba(174, 47, 52, 0.02)',
      headerBorderRadius: designTokens.borderRadius.lg,
    },
    Tag: {
      borderRadiusSM: designTokens.borderRadius.full,
    },
    Tabs: {
      inkBarColor: designTokens.colors.primary,
      itemSelectedColor: designTokens.colors.primary,
      itemHoverColor: designTokens.colors.primary,
    },
    Badge: {
      colorError: designTokens.colors.primary,
    },
    Progress: {
      defaultColor: designTokens.colors.primary,
    },
  },
};
